# Generated by Django 5.2.8 on 2025-12-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_meet_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="meet_link",
        ),
    ]
