# Generated by Django 5.2.8 on 2025-12-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_remove_appointment_meet_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="meet_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
