# Generated by Django 5.2.8 on 2025-12-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0005_appointment_completed_at_appointment_started_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
