# Generated by Django 5.2.8 on 2025-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_appointment_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("pending", "Pending"),
                    ("missed", "Missed"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
