# Generated by Django 5.2.8 on 2025-12-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_patientprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/doctors/"
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
