# Generated by Django 5.2.8 on 2025-12-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verification",
            old_name="is_verified",
            new_name="used",
        ),
        migrations.RemoveField(
            model_name="verification",
            name="otp",
        ),
        migrations.AddField(
            model_name="verification",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="verification",
            name="otp_hash",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
